server:
  port: 8082

spring:
  application:
    name: user-service
  
  config:
    import:
      - optional:aws-secretsmanager:oddiya/user-service/db
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:oddiya}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    properties:
      hibernate:
        default_schema: user_service
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.oddiya.user: DEBUG

