server:
  port: 8083

spring:
  application:
    name: plan-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:oddiya}
    username: ${DB_USER:oddiya_user}
    password: ${DB_PASSWORD:oddiya_password_dev}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    properties:
      hibernate:
        default_schema: plan_service
    hibernate:
      ddl-auto: validate
    show-sql: false

# LLM Agent configuration
llm:
  agent:
    base-url: ${LLM_AGENT_URL:http://localhost:8000}

# External APIs
kakao:
  local:
    api-key: ${KAKAO_LOCAL_API_KEY:your-api-key-here}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.oddiya.plan: DEBUG

