package com.oddiya.plan.dto;

import lombok.Data;

/**
 * Request DTO for Python LLM Agent.
 * Title will be auto-generated by Python service.
 */
@Data
public class LlmRequest {
    private String location;   // Destination city (e.g., "Seoul", "Busan")
    private String startDate;  // ISO format: "2025-12-01"
    private String endDate;    // ISO format: "2025-12-03"
    private String budget;     // Budget amount in KRW or "low"/"medium"/"high"
}

